### ISSUE TITLE
Setup difficulties

### ISSUE THREAD

**Issue by Stoffberg** [caddyserver/ingress#115]
I've deployed a Kubernetes cluster via the official [Microsoft guide](https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster?tabs=azure-cli), then I followed your instructions as far as I could. They are deployed on the same cluster, what do I still need to do to to be able to access the main application's external URL via HTTPS and be able to add my own domain.

I assume for adding your own domain I can just point the DNS records on my provider to the load balancer's external IP address and everything should just work. Some feedback on this would also be appreciated. 

Here are my `yaml` files:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: azure-vote-back
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-vote-back
    template:
        metadata:
            labels:
                app: azure-vote-back
        spec:
            nodeSelector:
                "beta.kubernetes.io/os": linux
            containers:
                - name: azure-vote-back
                  image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
                  env:
                      - name: ALLOW_EMPTY_PASSWORD
                        value: "yes"
                  ports:
                      - containerPort: 6379
                        name: redis
---
apiVersion: v1
kind: Service
metadata:
    name: azure-vote-back
spec:
    ports:
        - port: 6379
    selector:
        app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: azure-vote-front
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-vote-front
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: azure-vote-front
        spec:
            nodeSelector:
                "beta.kubernetes.io/os": linux
            containers:
                - name: azure-vote-front
                  image: crdb8732.azurecr.io/azure-vote-front:v1
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          cpu: 250m
                      limits:
                          cpu: 500m
                  env:
                      - name: REDIS
                        value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
    name: azure-vote-front
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: azure-vote-front
```

```yaml
---
# Source: caddy-ingress-controller/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: mycaddy-caddy-ingress-controller
    namespace: caddy-system
    labels:
        helm.sh/chart: caddy-ingress-controller-1.0.3
        app.kubernetes.io/name: caddy-ingress-controller
        app.kubernetes.io/instance: mycaddy
        app.kubernetes.io/version: "0.1.3"
        app.kubernetes.io/managed-by: Helm
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: caddy-ingress-controller
            app.kubernetes.io/instance: mycaddy
---
# Source: caddy-ingress-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
    name: caddy-ingress-controller
    namespace: caddy-system
    labels:
        helm.sh/chart: caddy-ingress-controller-1.0.3
        app.kubernetes.io/name: caddy-ingress-controller
        app.kubernetes.io/instance: mycaddy
        app.kubernetes.io/version: "0.1.3"
        app.kubernetes.io/managed-by: Helm
---
# Source: caddy-ingress-controller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: caddy-ingress-controller-configmap
    namespace: caddy-system
data:
    acmeCA: ""
    acmeEABKeyId: ""
    acmeEABMacKey: ""
    debug: "true"
    email: "********@*******.com" # <--- my email is here
    experimentalSmartSort: "false"
    metrics: "true"
    onDemandTLS: "true"
    proxyProtocol: "false"
---
# Source: caddy-ingress-controller/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: caddy-ingress-controller-role
    namespace: caddy-system
rules:
    - apiGroups:
          - ""
          - "networking.k8s.io"
          - "coordination.k8s.io"
      resources:
          - ingresses
          - ingresses/status
          - secrets
          - leases
      verbs: ["*"]
    - apiGroups:
          - ""
      resources:
          - services
          - pods
          - nodes
          - routes
          - extensions
          - configmaps
      verbs:
          - list
          - get
          - watch
---
# Source: caddy-ingress-controller/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: caddy-ingress-controller-role-binding
    namespace: caddy-system
roleRef:
    kind: ClusterRole
    name: caddy-ingress-controller-role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: caddy-ingress-controller
      namespace: caddy-system
---
# Source: caddy-ingress-controller/templates/loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
    name: mycaddy-caddy-ingress-controller
    namespace: caddy-system
    labels:
        helm.sh/chart: caddy-ingress-controller-1.0.3
        app.kubernetes.io/name: caddy-ingress-controller
        app.kubernetes.io/instance: mycaddy
        app.kubernetes.io/version: "0.1.3"
        app.kubernetes.io/managed-by: Helm
spec:
    type: "LoadBalancer"
    loadBalancerIP: #Deprecated in Kubernetes v1.24
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
        - name: https
          port: 443
          protocol: TCP
          targetPort: https
    selector:
        app.kubernetes.io/name: caddy-ingress-controller
        app.kubernetes.io/instance: mycaddy
---
# Source: caddy-ingress-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mycaddy-caddy-ingress-controller
    namespace: caddy-system
    labels:
        helm.sh/chart: caddy-ingress-controller-1.0.3
        app.kubernetes.io/name: caddy-ingress-controller
        app.kubernetes.io/instance: mycaddy
        app.kubernetes.io/version: "0.1.3"
        app.kubernetes.io/managed-by: Helm
spec:
    replicas: 2
    selector:
        matchLabels:
            app.kubernetes.io/name: caddy-ingress-controller
            app.kubernetes.io/instance: mycaddy
    template:
        metadata:
            labels:
                helm.sh/chart: caddy-ingress-controller-1.0.3
                app.kubernetes.io/name: caddy-ingress-controller
                app.kubernetes.io/instance: mycaddy
                app.kubernetes.io/version: "0.1.3"
                app.kubernetes.io/managed-by: Helm
        spec:
            serviceAccountName: caddy-ingress-controller
            securityContext: {}
            containers:
                - name: caddy-ingress-controller
                  securityContext:
                      allowPrivilegeEscalation: true
                      capabilities:
                          add:
                              - NET_BIND_SERVICE
                          drop:
                              - ALL
                      runAsGroup: 0
                      runAsUser: 0
                  image: "caddy/ingress:v0.1.3"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP
                      - name: https
                        containerPort: 443
                        protocol: TCP
                      - name: metrics
                        containerPort: 9765
                        protocol: TCP
                  resources: {}
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                  volumeMounts:
                      - name: tmp
                        mountPath: /tmp
                  args:
                      - -config-map=caddy-ingress-controller-configmap
                      - -class-name=caddy
                  readinessProbe:
                      initialDelaySeconds: 3
                      periodSeconds: 10
                      httpGet:
                          port: 9765
                          path: /healthz
            volumes:
                - name: tmp
                  emptyDir: {}
```

To help furthermore, I am getting this debug and error from looking into the pods:
```
{"level":"debug","ts":1675856842.9343529,"logger":"caddy.storage.secret_store","msg":"finding secret","name":"certificates/acme-v02.api.letsencrypt.org-directory/10.244.1.4/10.244.1.4.crt"}
{"level":"debug","ts":1675856842.946142,"logger":"tls.obtain","msg":"trying issuer 1/1","issuer":"acme-v02.api.letsencrypt.org-directory"}
{"level":"error","ts":1675856842.9461808,"logger":"tls.obtain","msg":"will retry","error":"[10.244.1.4] Obtain: subject does not qualify for a public certificate: 10.244.1.4","attempt":2,"retrying_in":120,"elapsed":60.021384952,"max_duration":2592000}
```

**Comment by RickFoland** [comment]
I'm not part of the team, but I might be able to help.

I think you're getting that error because you're attempting to connect to the cluster via IP (with no SNI), not a domain name. Caddy can't request certs for IP addresses so it complains.

The helm chart will request a load balancer from Azure when you deploy it (at least it does in AWS and GCP). You should be able to find the LB in Azure (I don't know where for Azure). You may be able to see the external IP or DN for the LB by running `kubectl get services -A`

You would point your domain to that load balancer. Then, when navigating to that domain via browser for the first time, Caddy would get the initial handshake with the domain in the SNI field and then use LE to request a cert for you.

I also had to create an ingress service definition to point Caddy requests to the backend pods. Something like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-caddy
  namespace: your-namespace
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-cluster-ip-service
                port:
                  number: 80
```
