### ISSUE TITLE
HTTPS errors with invalid URLs

### ISSUE THREAD

**Issue by timthelion** [caddyserver/ingress#120]
So this is a bit of a strange one, but we're using caddy ingress and we ended up with an invalid URL due to some configured payment portal. The invalid URLs are of the shape: `https://dpnk.dopracenakole.cz/platba_neuspesna/%transId%/34210-1J1676379637//105/`

The trouble is that `%transId%` should actually be just a number... The `%` signs are used as escape sequences in URLs and somewhere, somehow, caddy is misingesting this and just returning a blank page with no encryption:

![image](https://user-images.githubusercontent.com/1391608/218760455-30518a22-46c8-43ea-ad72-19fef829e7be.png)

 Here is the regex on our ingress:

```
  - host: dpnk.dopracenakole.cz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dpnk
            port:
                number: 8000
``` 

 https://github.com/auto-mat/k8s/blob/master/manifests/ingress/caddy.yaml#L452
 
 I'm pretty sure this is a pretty low priority bug. Like it doesn't actually effect us at all (we just need to yell at our payment portal for being broken). But I'm submitting it here because it sure took us a long time to debug and I thought someone else might find it when googling their weird-af problem.
