### ISSUE TITLE
Strip/rewrite a path?

### ISSUE THREAD

**Issue by RonquilloAeon** [caddyserver/ingress#202]
Hello! I am wondering if there's a way to strip/rewrite a path? I have the following ingress (Terraform). I need to strip `/gqldocs`. Unfortunately, I haven't been able to get the strip to work. I'm not sure if I'm setting the annotation correctly. Please help.

```
resource "kubernetes_ingress_v1" "staging_rewrite_ingress" {
  metadata {
    name = "rewrite-path-ingress"
    namespace = "staging"
    annotations = {
      "caddy.ingress.kubernetes.io/rewrite-strip-prefix" = "true"
    }
  }

  spec {
    ingress_class_name = "caddy"

    rule {
      host = "example.com"
      http {
        path {
          backend {
            service {
              name = "apollo-docs-new-svc"
              port {
                number = 80
              }
            }
          }
          path = "/gqldocs"
          path_type = "Prefix"
        }
      }
    }
  }
}
```

Here's the K8s equivalent:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    caddy.ingress.kubernetes.io/rewrite-strip-prefix: "true"
  name: rewrite-path-ingress
  namespace: staging
spec:
  ingressClassName: caddy
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: apollo-docs-new-svc
            port:
              number: 80
        path: /gqldocs
        pathType: Prefix
```
