### ISSUE TITLE
Cannot map IngressController to Ingress

### ISSUE THREAD

**Issue by hxjo** [caddyserver/ingress#241]
Hello,

First of all, my apologies if the problem here is dumb, I'm very new to Kubernetes.
I am trying to setup a simple ingress from a domain to a service, and for some reason it does not seem to work. 

```
cat deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 808
```

```
cat service.yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
```

```
cat ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  ingressClassName: caddy
  rules:
  - host: **MASKED**
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld-service
            port:
              number: 8080
```

```
kubectl get svc -n caddy-system
NAME                             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
caddy-caddy-ingress-controller   LoadBalancer   10.43.83.220   **MASKED**   80:30354/TCP,443:31216/TCP   15m
````

NSLOOKUP on the domain does point to the `hostname -I` ip on the VPS, which is also referenced as externalIP on the caddy ingress controller.

Caddy ingress server does seem to read the ingress:
```
{"level":"info","ts":1718608105.6925824,"caller":"controller/action_ingress.go:46","msg":"Ingress created (default/helloworld-ingress)"}
```
> [!NOTE]  
> When I try with the nginx ingress controller from taken from`https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml` (referencing the right externalIP too)
> (and by switching spec.ingressClassName to nginx in the Ingress), I can curl without issue.

Yet any curl on the hostname results in 404, and no log from the ingress controller.

Would any of you have any idea of what might be causing this ? Have I missed something ?

I am not on a managed kubernetes, I am on a private VPS.

I am using k3s.

If you need any more information to answer the question, please go for it.

Thank you very much for your time, have a nice day.
Thanks a lot to the contributors of this project.
