### ISSUE TITLE
custom certificate isn't working

### ISSUE THREAD

**Issue by taraszka** [caddyserver/ingress#277]
I followed the example with my own TLS certificate and got the following errors:
```
no certificate matching TLS ClientHello
```

The cert works as the same PEM used with a standalone Caddy (not an ingress), which works fine. I bet it comes from the Go library, as I couldn't find this error message in an ingress source code.

My `values.yaml`:
```
replicaCount: 1
ingressController:
  config:
    email: "hello@example.com"
    onDemandTLS: true
    onDemandAsk: 'http://answer-caddy-service.answer-caddy.svc:8080/ask'
loadBalancer:
  enabled: true
  annotations:
    "io.cilium/lb-ipam-ips": "10.10.10.1"
    "lbipam.cilium.io/sharing-key": "10101011"
    "lbipam.cilium.io/sharing-cross-namespace": '*'
```

The ingress service yaml that did not work:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example.com
  namespace: example
spec:
  ingressClassName: caddy
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
  tls:
    - secretName: mycerts
      hosts:
      - example.com
```

The secret `mycerts` exists in the example namespace and was created in the following way: 
```
kubectl create secret tls mycerts --key ./tls.key --cert ./tls.crt
```
