### ISSUE TITLE
How to set backend-protocol: "HTTPS"

### ISSUE THREAD

**Issue by samstride** [caddyserver/ingress#91]
Hi,

Thanks for maintaining this repo.

I am trying to use caddy ingress to expose the kubernetes dashboard.

With nginx, this annotation is needeed in the ingress:

```
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

Whats the equivalent for Caddy's ingress?

I am on GKE 1.22.8.

My ingress definition looks something like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  rules:
    - host: k8s.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443

```

Thanks.
